version: "3"
services:
    nginx:
        image: liteacz/nginx:1.19-local
        ports:
            - 8000:80
        volumes:
            - ./public:/var/www/public
        depends_on: 
            - php-fpm
    
    php-fpm:
        image: liteacz/php:8.0-fpm-local
        environment:
            FPM_ROOT_DIR: public
        volumes:
            - .:/var/www